import type { Metadata } from "next";
// Depilation mode: sem estilos globais

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className="antialiased font-sans text-zinc-900" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
