import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
<<<<<<< HEAD
    <html lang="pt-BR" suppressHydrationWarning>
      <body className="antialiased font-sans text-zinc-900 dark:text-zinc-50" suppressHydrationWarning>
        {children}
=======
    <html lang="pt-BR">
      <body className={`antialiased bg-zinc-50 text-zinc-900`}>
        <header className="sticky top-0 z-20 border-b border-zinc-200/70 bg-white/80 backdrop-blur-md dark:border-zinc-800 dark:bg-black/60">
          <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-3">
            <a href="/" className="font-semibold">Mznet</a>
            <div className="flex items-center gap-4 text-sm">
              <a className="hover:underline" href="/login">Login</a>
              <a className="hover:underline" href="/perfil">Perfil</a>
              <a className="hover:underline" href="/kanban">Kanban</a>
            </div>
          </nav>
        </header>
        <main className="mx-auto min-h-[calc(100dvh-56px)] max-w-6xl px-6 py-6">{children}</main>
>>>>>>> Kanban
      </body>
    </html>
  );
}
